name: 'Bundle Release Companion'
description: 'Release Arturo Bundle'
branding:
    icon: package
    color: purple
inputs:
    token:
        description: >-
            The GITHUB_TOKEN secret.
        required: true
    name:
        description: >-
            The name of the application.
        required: true
    notes:
        description: >-
            The body for the releases . If this is not set, then the `github.ref` will be used.
        default: ''
runs:
    using: "composite"
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
            path: ./assets
            pattern: ${{ inputs.name }}-*
            merge-multiple: true
            github-token: ${{ inputs.token }}

      - name: Debug environment
        run: |
            echo "NAME: ${{ inputs.name }}"
            echo "VERSION: ${{ github.ref_name }}"
            ls -laR ./assets
        shell: bash
    
      - name: Upload release assets
        run: |
            if [ "${{ inputs.notes }}" = "auto" ]; then
              DESC="--generate-notes"
            elif [ "${{ inputs.notes }}" = "" ]; then
              DESC=""
            else
              DESC="--notes '${{ inputs.notes }}'"
            fi
            gh release create ${{ github.ref_name }} $DESC ./assets/*
        env:
            GITHUB_TOKEN: ${{ inputs.token }}
        shell: bash