name: 'Subaction'
description: 'Release Arturo Bundle'
inputs:
    token:
        description: >-
            The GITHUB_TOKEN secret.
        required: true
    name:
        description: >-
            The name of the application.
        required: true
    description:
        description: >-
            The body for the releases . If this is not set, then the `github.ref` will be used.
        default: ''
runs:
    using: "composite"
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
            path: ./assets
            github-token: ${{ inputs.token }}

      - name: Debug environment
        run: |
            echo "NAME: ${{ inputs.name }}"
            echo "VERSION: ${{ github.ref_name }}"
            ls -laR ./assets
        shell: bash

      - name: Fetch description
        run: |
          if [ "${{ inputs.description }}" = "" ]; then
              echo "RELDESC=${{ github.ref }}" >> $GITHUB_ENV
          else
              echo "RELDESC=${{ inputs.description }}" >> $GITHUB_ENV
          fi
        shell: bash

    #   - name: Create Release
    #     id: create-release
    #     uses: actions/create-release@v1
    #     env:
    #         GITHUB_TOKEN: ${{ inputs.token }}
    #     with:
    #         tag_name: ${{ github.ref_name }}
    #         release_name: "${{ inputs.name }} ${{ inputs.version }}"
    #         body: |
    #             ${{ inputs.name }} ${{ inputs.version }} Release
    #             ${{ env.RELDESC }}
    #         draft: false
    #         prerelease: false
    
      - name: Upload release assets
        run: |
            gh release create ${{ github.ref_name }} ./assets/*
        env:
            GITHUB_TOKEN: ${{ inputs.token }}
        shell: bash
        
    #   - name: Upload Release Assets
    #     id: upload-release-assets
    #     uses: dwenegar/upload-release-assets@v1
    #     env:
    #         GITHUB_TOKEN: ${{ inputs.token }}
    #     with:
    #         release_id: ${{ steps.create-release.outputs.id }}
    #         assets_path: ./assets  

branding:
    icon: 'package'
    color: 'purple'
    